/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'MarkPerry' at '24/07/14 8:15 PM' with Gradle 2.0
 *
 * @author MarkPerry, @date 24/07/14 8:15 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
