/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'MarkPerry' at '24/07/14 8:15 PM' with Gradle 2.0
 *
 * @author MarkPerry, @date 24/07/14 8:15 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
